### ISSUE TITLE
how to construct qt apps?

### ISSUE THREAD

**Issue by michael1888** [varghes/QNX-QT-Apps#1]
Hi Varghes,

I am testing QT on BBB with QNX now, and caught your exampled QNX-QT-Apps. First of all, thank you for the sharing.

I would like to ask how did you construct these apps. Do I need to install qt-everywhere-opensource-src-4.7.1 on Ubuntu,  then use qtdesigner or qvfb tools to design the project UI, and later migrate to QNX momentics IDE? Or can I simply use qt_qnx_host_linux_x86.tar.gz installation to design UI inside QNX momentics IDE?

Please help to address in details. Thanks in advance,

Mike

**Comment by varghes** [comment]
Hi Mike,

Originally these apps where built for linux /Windows OS, see the readme file to get the details about each apps.  The credits goes to their original authors.
 
I have compiled them to work for QNX ARM V7   , compilation procedures  , QNX QT libraries links are given ( https://drive.google.com/open?id=0B02sL8YIqsjCNS1ZWFNkQzRRY0E ) . Compiled executable is also available in the "exe" folder , you can run them on BBB . my other project "BeagleboneBlack-QNX-QT" contains all the script (.build) to run QT on QNX . 

Initially  you can design the basic  UI under Windows/Linux , then move the code to QNX & add the codes/drivers specific to QNX . again Its up to your choice .  

Varghese
